Bench/urls.py
from django.urls import path

from . import views
app_name = 'Bench'
urlpatterns = [
    # path('', views.home, name='home'),
    # path('bench/', views.bench_emp, name='bench_emp'),
    path('manage_emp/', views.manage_emp, name='manage_emp'),
    path('create_emp/', views.create_emp, name='create_emp'),
    path('delete_emp/<int:id>', views.delete_emp, name='delete_emp'),
    path('edit_emp/<int:id>', views.edit_emp, name='edit_emp'),
    
]

Bench_mgnt/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bench/', include('Bench.urls')),
    
]

Bench/models.py
from django.db import models
import datetime
# Create your models here.



class Employee(models.Model):
    name = models.CharField(max_length=50,null=True)
    team_leader=models.CharField(max_length=50,null=True)
    designation = models.CharField(max_length=50,null=True)
    experience = models.CharField(max_length=20,null=True)
    stack = models.CharField(max_length=50,null=True)        
    # secondary_skills = models.CharField(max_length=50,null=True)
    skills = models.CharField(max_length=50,null=True)
    resource_status = models.CharField(max_length=50,null=True)
    date_of_joining= models.CharField(max_length=50,null=True)
    # date_of_joining= models.DateField(blank=True,default=datetime.date.today)
    
    # work_status = models.CharField(max_length=50,null=True) 
    # billing = models.BooleanField(default=False,null=True)
    # pay_value = models.FloatField(null=True)
    # proxy = models.BooleanField(default=False,null=True)
    profile_link = models.CharField(max_length=50,null=True)
    created_at=models.DateTimeField(auto_now_add=True)

Bench/views.py
from django.shortcuts import render, redirect, get_object_or_404
import pandas as pd
import re
from Bench.models import Employee
# Create your views here.
import os
import pandas as pd 
import numpy as np
from datetime import datetime




# def bench_emp(request):
#     if request.method == 'GET':
#         # df=pd.read_csv(r'D:\twilight\python\Bench_mgnt\Bench\vasanth_sir_team.csv')
#         # df.where(pd.notnull(df), None)
#         # df['Team Leader Name']='Mr.Vasanth'
#         # df1 = df.replace(np.nan, '', regex=True)
#         # for i in df1.to_dict('records'):
#         #     print(i)
#         #     Employee.objects.create(
#         #         name=i['Team Members'],
#         #         team_leader=i['Team Leader Name'],
#         #         designation=i['Designation'] or None,
#         #         experience=i['Experience']or None,
#         #         stack=i['Stack']or None,
#         #         skills=i['Skills']or None,
#         #         resource_status=i['Resource Status']or None,
#         #         date_of_joining=i['Date Of Joining']or None,
                
#         #     )
#         employes = Employee.objects.all()
#         context = {'employes': employes}
#         return render(request, 'benchrows.html', context)
#     elif request.method == 'POST':
#         employes = Employee.objects.filter(primary_skills=request.POST['search']).order_by(
#             "-experience") | Employee.objects.filter(secondary_skills=request.POST['search']).order_by("-experience")
#         context = {"employes": employes, 'form_data': request.POST['search']}
#         return render(request, 'benchrows.html', context)


def manage_emp(request):
    if request.method == 'GET':
        employes = Employee.objects.all()
        team_leader= Employee.objects.order_by().values('team_leader').distinct()
        designation= Employee.objects.order_by().values('designation').distinct()
        stack= Employee.objects.order_by().values('stack').distinct()
        
        print(designation)
        
        resource_status= Employee.objects.order_by().values('resource_status').distinct()
        context = {'employes': employes,'stack':stack,'team_leader':team_leader,'designation':designation,'resource_status':resource_status}
        return render(request, 'employes.html', context)


def create_emp(request):
    if request.method == 'GET':
        return render(request, 'create_emp.html')
    elif request.method == 'POST':
        emp = Employee()
        emp.name = request.POST['name']
        emp.experience = request.POST['experience']
        emp.team_leader = request.POST['team_leader']
        emp.designation = request.POST['designation']
        emp.date_of_joining=datetime.strptime(request.POST['date_of_joining'], "%Y-%m-%d")
        emp.resource_status = request.POST['resource_status']
        emp.skills = request.POST['skills']
        emp.profile_link = request.POST['profile_link']
        emp.save()
        return redirect('Bench:manage_emp')


def delete_emp(request, id):
    get_object_or_404(Employee, id=id).delete()
    return redirect('Bench:manage_emp')

    # msg=messages.error(request, 'This  has been deleted.')


def edit_emp(request, id):
    if request.method == 'GET':
        emp = Employee.objects.get(id=id)
        return render(request, 'create_emp.html',context = {'emp':emp})
    elif request.method == 'POST':
        # print(request.POST['name'])
        Employee.objects.filter(id=id).update(
        name = request.POST['name'],
        experience = request.POST['experience'],
        team_leader = request.POST['team_leader'],
        designation = request.POST['designation'],
        date_of_joining=datetime.strptime(request.POST['date_of_joining'], "%Y-%m-%d"),
        resource_status = request.POST['resource_status'],
        skills = request.POST['skills'],
        profile_link = request.POST['profile_link'],
        )
        return redirect('Bench:manage_emp')

Bench/templates/bench.html
<body>
    {% extends 'main.html' %} {% block content %}
    <!-- <div class="h-10 bg-light p-4 container-fluid">
        <h1 class="text-center ">Bench</h1>
    </div> -->
    <div class="container">
        <div class="d-flex mt-2 flex-row justify-content-center">
            <form class="form" method="POST" enctype="multipart/form-data" action="{% url 'Bench:bench_emp' %}">
                {% csrf_token %}

                <div class="d-flex mt-2 flex-row justify-content-center">
                    <input type="text" value="{{form_data}}" class="form-control mr-2" placeholder="Search" name="search" />
                    <button type="submit" style="width:15vw" class="form-control btn-sm btn-success">Search</button>
                </div>
            </form>

        </div>

        {% block benchrows %} {% endblock %}
    </div>
</body>
<style>
    .fname-title {
        color: #585856;
        font-size: 22px;
        font-weight: 500;
    }
    
    .bench-topnav-nav-link {
        margin-right: 1.5em;
        padding: 8px 16px;
        background-color: #00aade;
        color: white;
        font-weight: 500;
    }
    
    .bench-topnav-nav-link:hover {
        color: black!important;
        /* background-color: #00aade; */
    }
    
    .Bench-logoImage {
        width: 100px;
        height: auto;
        margin-left: 1.5em;
    }
    
    .job-div-1 {
        padding: 15px;
        background: #fff;
        margin: 15px 0;
        border: 1px solid #e0e0e0;
        /* padding: 2em; */
    }
    
    .secondblock-bench {
        padding: 2.5em;
        display: flex;
        flex-direction: column;
        align-content: center;
        justify-content: center;
    }
    
    .p-text {
        text-align: center;
        font-size: 17px;
        line-height: 1.5;
        color: white;
        /* width: 80%; */
    }
    
    .secondblock-bench-margin {
        margin-left: 3em;
        margin-right: 3em;
    }
    
    .submit-bench {
        color: #fff;
        padding: 8px 20px 9px 20px;
        background: #00aade;
        font-size: 15px;
        border: none;
    }
    
    .secondBlock-bench {
        margin-top: 2em;
        padding: 10px 8px 7px 10px;
        background: #9b9c9a;
        margin-bottom: 15px;
        margin-right: 6em;
    }
    
    .Bench-job-row-main {
        width: 100%;
        margin-right: 5.6em;
    }
    
    .searchBar-row {
        row-gap: 0px;
    }
    
    .form-home-search {
        padding: 10px 8px 7px 10px;
        background: #9b9c9a;
        margin-bottom: 15px;
    }
    
    .para {
        font-weight: 400!important;
        margin-top: 8px;
    }
    
    .job-div-1 p {
        font-weight: 400;
        margin-bottom: 0;
        margin-top: 0;
    }
    
    .block-skill {
        background: #787b78;
        padding: 0 10px;
        color: #fff;
        border-radius: 4px;
        margin: 3px 3px;
        display: inline-block;
    }
    
    .margin-row-div {
        margin-left: -15px;
        /* margin-right: -15px; */
        padding: 2em;
    }
    
    .bench-filter-main {
        padding-right: 15px;
        padding-left: 15px;
        margin-right: auto;
        margin-left: auto;
        padding: 2em;
    }
    
    .bench-filter-main-row {
        margin-left: 4em!important;
    }
    
    .bench-col-form {
        padding: 1em!important;
    }
    
    .benchjobrow-Link {
        color: black;
    }
    
    .benchjobrow-Link:hover {
        color: black;
    }
    
    @media screen and (max-width:565px) {
        .margin-row-div {
            margin: 0 0 0 0!important;
        }
        .secondBlock-bench {
            margin-right: 0!important;
        }
        .bench-filter-main-row {
            margin-left: 0!important;
        }
        .Bench-job-row-main {
            width: 100%;
            margin-right: 0!important;
        }
        .bench-topnav-nav-link {
            margin-right: 1.5em;
            padding: 0px;
            background-color: transparent;
            color: black;
            font-weight: 500;
        }
        .bench-topnav-nav-link:hover {
            color: black!important;
            /* background-color: #00aade; */
        }
    }
</style>
{% endblock %}

Bench/templates/create_emp.html
<body>
    {% extends 'main.html' %} {% block content %}
    <div class="container-fluid d-flex flex-row align-items-center justify-content-center">
        <div class="mt-5 shadow p-3 mb-5 bg-white rounded">
            {% if emp.id is not none %}
            <form method="POST" action="{% url 'Bench:edit_emp' emp.id %}" enctype="multipart/form-data" autocomplete="off">
                {% else %}
                <form method="POST" action="{% url 'Bench:create_emp' %}" enctype="multipart/form-data" autocomplete="off">
                    {% endif %} {% csrf_token %}
                    <div class="form-row">
                        <div class="form-group col-md-4">
                            <label for="">Name</label>
                            <input type="text" autocomplete="off" value="{{emp.name}}" name="name" class="form-control" placeholder="Employee Name">
                        </div>
                        <div class="form-group col-md-4">
                            <label for="inputPassword4">Designation</label>
                            <select id="" name="designation" class="form-control">
                                {% if emp.id is not none %}
                        <option selected value="{{emp.designation}}">{{emp.designation}}</option>
                    <option value="Software Engineer">Software Engineer</option>
                      <option value="iOS Team lead">iOS Team lead</option>
                      <option value="Trainee">Trainee</option>
                      <option value="Leader">Leader</option>
                      <option value="Front-End Developer">Front-End Developer</option>
                      <option value="Back-End Developer">Back-End Developer</option>
                      <option value="Graphics Designer">Graphics Designer</option>
                      <option value="Full Stack Developer">Full Stack Developer</option>
                      <option value="Quality Analyst">Quality Analyst</option>


                                    {% else %}
                      <option selected>---Select----</option>
                                        {% endif %}

                    <option value="Software Engineer">Software Engineer</option>
                    <option value="iOS Team lead">iOS Team lead</option>
                    <option value="Trainee">Trainee</option>
                    <option value="Leader">Leader</option>
                    <option value="Front-End Developer">Front-End Developer</option>
                    <option value="Back-End Developer">Back-End Developer</option>
                    <option value="Graphics Designer">Graphics Designer</option>
                    <option value="Full Stack Developer">Full Stack Developer</option>
                    <option value="Quality Analyst">Quality Analyst</option>
                  
                    </select>
                        </div>
                        <div class="form-group col-md-4">
                            <label for="inputPassword4">Teamleader</label>
                            <select id="" name="team_leader" class="form-control">
                                {% if emp.id is not none %}
                        <option selected value="{{emp.team_leader}}">{{emp.team_leader}}</option>
                        <option value="Balachandar">Balachandar</option>
                      <option value="Balaji">Balaji</option>
                      <option value="Damodharan">Damodharan</option>
                      <option value="Fernandus">Fernandus</option>
                      <option value="Indhumathy">Indhumathy</option>
                      <option value="Kautham">Kautham</option>
                      <option value="Keerthiharan">Keerthiharan</option>
                      <option value="Mohanraj">Mohanraj</option>
                      <option value="Muruganadham">Muruganadham</option>
                      <option value="Manikam">Manikam</option>
                      <option value="Sundar">Sundar</option>
                      <option value="Valarmathy">Valarmathy</option>
                      <option value="Vasanth">Vasanth</option>
                      <option value="VijayAnand">VijayAnand</option>
                      <option value="Vijayakumar">Vijayakumar</option>
                      <option value="Manibalan">Manibalan</option>

                                    {% else %}
                      <option selected>---Select----</option>
                                        {% endif %}

                        <option value="Balachandar">Balachandar</option>
                        <option value="Balaji">Balaji</option>
                        <option value="Damodharan">Damodharan</option>
                        <option value="Fernandus">Fernandus</option>
                        <option value="Indhumathy">Indhumathy</option>
                        <option value="Kautham">Kautham</option>
                        <option value="Keerthiharan">Keerthiharan</option>
                        <option value="Mohanraj">Mohanraj</option>
                        <option value="Muruganadham">Muruganadham</option>
                        <option value="Manikam">Manikam</option>
                        <option value="Sundar">Sundar</option>
                        <option value="Valarmathy">Valarmathy</option>
                        <option value="Vasanth">Vasanth</option>
                        <option value="VijayAnand">VijayAnand</option>
                        <option value="Vijayakumar">Vijayakumar</option>
                        <option value="Manibalan">Manibalan</option>
                  
                    </select>

                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="">Experience</label>
                            <select id="" name="experience" class="form-control">
                                {% if emp.id is not none %}
                        <option selected value="{{emp.experience}}">{{emp.experience}}</option>
                        <option value="0-12 months">0-12 months</option>
                      <option value="1-2 years">1-2 years</option>
                      <option value="2-3 years">2-3 years</option>
                      <option value="3-4 years">3-4 years</option>
                      <option value="4-5 years">4-5 years</option>
                      <option value="5 years above">5 years above</option>

                                    {% else %}
                      <option selected>---Select----</option>
                                        {% endif %}

                        <option value="0-12 months">0-12 months</option>
                        <option value="1-2 years">1-2 years</option>
                        <option value="2-3 years">2-3 years</option>
                        <option value="3-4 years">3-4 years</option>
                        <option value="4-5 years">4-5 years</option>
                        <option value="5 years above">5 years above</option>

                  
                    </select>
                        </div>
                        <div class="form-group col-md-4">
                            <label for="">Resource</label>
                            <select id="" name="resource_status" class="form-control">
                                {% if emp.id is not none %}
                        <option selected value="{{emp.resource_status}}">{{emp.resource_status}}</option>
                        <option value="Dedicated Billable">Dedicated Billable</option>
                      <option value="Fixed Billable">Fixed Billable</option>
                      <option value="Fixed Non-Billable">Fixed Non-Billable</option>
                      <option value="Dedicated Non-Billable">Dedicated Non-Billable</option>
                      <option value="Dedicated proxy">Dedicated proxy</option>
                      <option value="Bench">Bench</option>
                      <option value="Training">training</option>

                                    {% else %}
                      <option selected>---Select----</option>
                                        {% endif %}

                      <option value="Dedicated Billable">Dedicated Billable</option>
                      <option value="Fixed Billable">Fixed Billable</option>
                      <option value="Fixed Non-Billable">Fixed Non-Billable</option>
                      <option value="Dedicated Non-Billable">Dedicated Non-Billable</option>
                      <option value="Dedicated proxy">Dedicated proxy</option>
                      <option value="Bench">Bench</option>
                      <option value="Training">training</option>
                    </select>
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="">Stack</label>
                            <select id="" name="stack" class="form-control">
                                {% if emp.id is not none %}
                        <option selected value="{{emp.stack}}">{{emp.stack}}</option>
                        <option value="DotNet (.Net)">DotNet (.Net)</option>
                      <option value="Android">Android</option>
                      <option value="Angular">Angular</option>
                      <option value="AWS Node">AWS Node</option>
                      <option value="Back-End">Back-End</option>
                      <option value="DotNet">DotNet </option>
                      <option value="Front-End">Front-End</option>
                      <option value="Front-End(IOS)">Front-End(IOS)</option>
                      <option value="Front-End(Android)">Front-End(Android)</option>
                      <option value="Flutter">Flutter</option>
                      <option value="FullStack">FullStack</option>
                      <option value="functioning and Non functioning testing">functioning and Non functioning testing</option>
                      <option value="iOS">iOS</option>
                      <option value="React JS">React JS</option>
                      <option value="React Native">React Native</option>
                      <option value="Unity">Unity</option>
                      <option value="UI">UI</option>

                      <option value="QA">QA</option>
                      <option value="UX Graphics Design">UX Graphics Design</option>
                      

                                    {% else %}
                      <option selected>---Select----</option>
                                        {% endif %}

                                        <option value="DotNet (.Net)">DotNet (.Net)</option>
                                        <option value="Android">Android</option>
                                        <option value="Angular">Angular</option>
                                        <option value="AWS Node">AWS Node</option>
                                        <option value="Back-End">Back-End</option>
                                        <option value="DotNet">DotNet </option>
                                        <option value="Front-End">Front-End</option>
                                        <option value="Front-End(IOS)">Front-End(IOS)</option>
                                        <option value="Front-End(Android)">Front-End(Android)</option>
                                        <option value="Flutter">Flutter</option>
                                        <option value="FullStack">FullStack</option>
                                        <option value="functioning and Non functioning testing">functioning and Non functioning testing</option>
                                        <option value="iOS">iOS</option>
                                        <option value="React JS">React JS</option>
                                        <option value="React Native">React Native</option>
                                        <option value="QA">QA</option>
                                        <option value="Unity">Unity</option>
                                        <option value="UI">UI</option>

                                        <option value="UX Graphics Design">UX Graphics Design</option>
                    </select>
                        </div>
                        <div class="form-group col-md-6">
                            <label for="inputPassword4">Date of joining</label>
                            <input type="date" class="form-control" value="{{emp.date_of_joining}}" name="date_of_joining" placeholder="">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="">Key Skills</label>
                        <input type="text" class="form-control" id="" value="{{emp.skills}}" name="skills" placeholder="key Skills">
                    </div>
                    <div class="form-row">

                        <div class="form-group col-md-12">
                            <label for="">Profile Link</label>
                            <input type="text" value="{{emp.profile_link}}" class="form-control" name="profile_link" placeholder="">
                        </div>
                    </div>
                    <button type="submit" class="btn btn-success float-right">Submit</button>
                </form>
        </div>
    </div>
    {% endblock %}
</body>

Bench/templates/employes.html
<body>
    {% extends 'main.html' %} {% block content %}
    <div class="row m-3 d-flex flex-row justify-content-end">
        <a href="{% url 'Bench:create_emp' %}" class="btn w-15 btn-success">Add Employee</a
    >
  </div>
    <div class="container-fluid p-4">

       
    <div class="table-responsive">
        <table id="example" class="table table-hover ">
            <thead>
                <tr>
                    <th>#</th>
                    <td>
                        <div id="list1" class="dropdown-check-list" tabindex="100">
                            <span class="anchor">Teamleader</span>
                            <ul class="items">
                                {% for item in team_leader %}
                                <li style='list-style-type:none;'> <input type="checkbox" class="filter-checkbox-tl" value="{{item.team_leader}}" /> {{item.team_leader}}
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </td>
                    <th>Name</th>
                    <td>
                        <div id="list2" class="dropdown-check-list" tabindex="100">
                            <span class="anchor">Designation</span>
                            <ul class="items">
                                {% for item in designation%}
                                <li style='list-style-type:none;'> <input type="checkbox" class="filter-checkbox-designation" value="{{item.designation}}" /> {{item.designation}}
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </td>
                    <th>Experience</th>
                    <td>
                        <div id="list3" class="dropdown-check-list" tabindex="100">
                            <span class="anchor">Stack</span>
                            <ul class="items">
                                {% for item in stack%}
                                <li style='list-style-type:none;'> <input type="checkbox" class="filter-checkbox-stack" value="{{item.stack}}" /> {{item.stack}}
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </td>
                    <td>
                        <div id="list4" class="dropdown-check-list" tabindex="100">
                            <span class="anchor">Resource</span>
                            <ul class="items">
                                {% for item in resource_status%}
                                <li style='list-style-type:none;'> <input type="checkbox" class="filter-checkbox-resource" value="{{item.resource_status}}" /> {{item.resource_status}}
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </td>
                    <th>Skills</th>
                    <th>DOJ</th>

                    <th>Actions</th>
                    

                </tr>
               

            </thead>
            <tbody>

                {% for employe in employes %}
                <tr>
                    <th>{{forloop.counter}}</th>
                    <td>{{employe.team_leader}}</td>
                    <td>{{employe.name}}</td>
                    <td>{{employe.designation}}</td>
                    <td>{{employe.experience}}</td>
                    <td>{{employe.stack}}</td>
                    <td>{{employe.resource_status}}</td>
                    <td>{{employe.skills}}</td>
                    <td>{{employe.date_of_joining}}</td>
                    <td>
                        <a href="{% url 'Bench:edit_emp' employe.id %}">Edit</a>
        <a href="{% url 'Bench:delete_emp' employe.id %}">Delete</a>
        </td>
        </tr>
        {% endfor %}
        </tbody>
        </table>
    </div>


    </div>
    <style>
        .dropdown-check-list {
            display: inline-block;
        }
        
        .buttons-excel {
            background-color: #0094ff;
            margin: 10px;
            border: none;
        }
        
        .buttons-csv {
            background-color: #5fdb6f;
            margin: 10px;
            border: none;
        }
        
        .buttons-copy {
            background-color: #788128;
            margin: 10px;
            border: none;
        }
        
        #example_filter,
        #example_paginate {
            float: right;
        }
        
        .dropdown-check-list .anchor {
            position: relative;
            cursor: pointer;
            display: inline-block;
            padding: 5px 50px 5px 10px;
            border: 1px solid #ccc;
        }
        
        .dropdown-check-list .anchor:after {
            position: absolute;
            content: "";
            border-left: 2px solid black;
            border-top: 2px solid black;
            padding: 5px;
            right: 10px;
            top: 20%;
            -moz-transform: rotate(-135deg);
            -ms-transform: rotate(-135deg);
            -o-transform: rotate(-135deg);
            -webkit-transform: rotate(-135deg);
            transform: rotate(-135deg);
        }
        
        .dropdown-check-list .anchor:active:after {
            right: 8px;
            top: 21%;
        }
        
        .dropdown-check-list ul.items {
            padding: 2px;
            display: none;
            margin: 0;
            border: 1px solid #ccc;
            border-top: none;
            z-index: 1;
            position: absolute;
            background: #fff;
            width: 15vw;
        }
        
        .dropdown-check-list ul.items li {
            list-style: none;
        }
        
        .dropdown-check-list.visible .anchor {
            color: #0094ff;
        }
        
        .dropdown-check-list.visible .items {
            display: block;
        }
    </style>
    <script>
        var checkList1 = document.getElementById('list1');
        checkList1.getElementsByClassName('anchor')[0].onclick = function(evt) {
            if (checkList1.classList.contains('visible'))
                checkList1.classList.remove('visible');
            else
                checkList1.classList.add('visible');
        }
        var checkList2 = document.getElementById('list2');
        checkList2.getElementsByClassName('anchor')[0].onclick = function(evt) {
            if (checkList2.classList.contains('visible'))
                checkList2.classList.remove('visible');
            else
                checkList2.classList.add('visible');
        }
        var checkList3 = document.getElementById('list3');
        checkList3.getElementsByClassName('anchor')[0].onclick = function(evt) {
            if (checkList3.classList.contains('visible'))
                checkList3.classList.remove('visible');
            else
                checkList3.classList.add('visible');
        }
        var checkList4 = document.getElementById('list4');
        checkList4.getElementsByClassName('anchor')[0].onclick = function(evt) {
            if (checkList4.classList.contains('visible'))
                checkList4.classList.remove('visible');
            else
                checkList4.classList.add('visible');
        }
    </script>
    {% endblock %}


</body>